### ISSUE TITLE
TODO list for draft-11

### ISSUE THREAD

**Issue by martinthomson** [ekr/minq#65]
## P1 - Will break if not fixed

- [ ] BLOCKED frame includes reason for blocking
- [ ] Remove payload from PING
- [ ] Parse PATH_CHALLENGE/PATH_RESPONSE
- [ ] ACK frame is now 0xd
- [ ] Connection ID rework (two values, varlen, handshake key changes, etc...)
- [ ] Add length to long packet header

## P2 - Might break if not fixed

- [ ] Max stream count transport parameters (currently max stream ID)
- [ ] Generate PATH_RESPONSE
- [ ] Send only 3 packets in server handshake (implies use of PATH_CHALLENGE or HRR - Ugh)
- [ ] Exempt stream 0 from flow control (check this)
- [ ] Send ACK in Retry packet

## P3 - OK without

- [ ] Send ACK delay transport parameter
- [ ] Grease version negotiation
- [ ] Allow empty STREAM frames (this is in -12)
- [ ] Remove implicit open (might return after Kista)
- [ ] Send CONNECTION_CLOSE when handshake fails
- [ ] Server preferred address
